# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-04-25 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_id', models.CharField(max_length=16, verbose_name='员工账号')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('travel_num', models.IntegerField(verbose_name='出差天数')),
                ('travel_fund', models.IntegerField(verbose_name='出差补贴')),
                ('travel_desc', models.CharField(max_length=256, verbose_name='出差事项说明')),
            ],
            options={
                'verbose_name': '员工出差信息',
                'verbose_name_plural': '员工出差信息',
            },
        ),
    ]
