# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-04-25 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_id', models.CharField(max_length=16, verbose_name='员工账号')),
                ('dept_id', models.IntegerField(verbose_name='部门ID')),
                ('post_id', models.IntegerField(verbose_name='岗位ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('attendance', models.IntegerField(verbose_name='出勤天数')),
                ('travel_num', models.IntegerField(verbose_name='出差天数')),
                ('basic_wage', models.IntegerField(verbose_name='基本工资')),
                ('performance', models.IntegerField(verbose_name='绩效奖金')),
                ('allowance', models.IntegerField(verbose_name='津贴')),
                ('insurance', models.FloatField(max_length=16, verbose_name='保险')),
                ('provident_fund', models.IntegerField(verbose_name='公积金')),
                ('travel_fund', models.IntegerField(verbose_name='出差补贴')),
                ('pre_tax_wages', models.FloatField(max_length=32, verbose_name='税前工资')),
                ('actual_salary', models.FloatField(max_length=32, verbose_name='实发工资')),
            ],
            options={
                'verbose_name': '员工薪资信息',
                'verbose_name_plural': '员工薪资信息',
            },
        ),
    ]
