# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-04-25 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PositionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=32, verbose_name='职位名称')),
                ('post_level', models.IntegerField(verbose_name='岗位级别')),
                ('salary_standard', models.IntegerField(verbose_name='薪资标准')),
            ],
            options={
                'verbose_name': '岗位信息',
                'verbose_name_plural': '岗位信息',
            },
        ),
    ]
