# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-04-25 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeptInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50, verbose_name='部门名称')),
                ('dept_desc', models.CharField(max_length=2000, verbose_name='部门描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '部门信息',
                'verbose_name_plural': '部门信息',
            },
        ),
    ]
